# Generated by Django 4.2.30 on 2026-10-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_biographie'),
    ]

    operations = [
        migrations.AddField(
            model_name='musique',
            name='lien_spotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
